ServerName localhost
DocumentRoot /app
DirectoryIndex index.php

LoadModule php_module modules/libphp83.so
AddHandler php-script .php

<Directory /app>
    AllowOverride All
    Require all granted
</Directory>