<?php

require_once __DIR__ . '/db.php';

function getFallbackProducts(): array
{
    return [
        [
            'id' => 1,
            'name' => '2026 Black Phantom Sedan',
            'slug' => '2026-black-phantom-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 128500.00,
            'short_description' => 'Matte black finish, V12 engine, handcrafted interior.',
            'full_description' => 'A flagship luxury sedan combining a commanding matte-black presence with a handcrafted cabin and effortless long-distance comfort.',
            'image_url' => 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Obsidian Black',
            'interior_color' => 'Chestnut Leather',
            'engine' => '6.0L Twin-Turbo V12',
            'horsepower' => 563,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 5,
            'featured' => 1,
        ],
        [
            'id' => 2,
            'name' => '2026 Silver Ghost SUV',
            'slug' => '2026-silver-ghost-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 119900.00,
            'short_description' => 'Premium grey, all-wheel drive, panoramic sunroof.',
            'full_description' => 'A premium SUV designed for confident travel with all-wheel traction, a panoramic roofline, and a tech-rich interior.',
            'image_url' => 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Sterling Silver',
            'interior_color' => 'Slate Leather',
            'engine' => '4.4L Twin-Turbo V8',
            'horsepower' => 523,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 7,
            'featured' => 1,
        ],
        [
            'id' => 3,
            'name' => '2026 White Lightning Coupe',
            'slug' => '2026-white-lightning-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 137400.00,
            'short_description' => 'Pure white, carbon fiber body, sport-tuned suspension.',
            'full_description' => 'An expressive grand touring coupe with a lightweight carbon-fiber body, razor-sharp handling, and elegant interior finishes.',
            'image_url' => 'https://images.unsplash.com/photo-1461632830798-3adb3034e4c8?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Pearl White',
            'interior_color' => 'Black Alcantara',
            'engine' => '4.0L Twin-Turbo V8',
            'horsepower' => 612,
            'transmission' => '7-Speed Dual Clutch',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 4,
            'featured' => 1,
        ],
        [
            'id' => 4,
            'name' => '2026 Midnight Reserve Sedan',
            'slug' => '2026-midnight-reserve-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 116800.00,
            'short_description' => 'Executive comfort with adaptive suspension and navy leather trim.',
            'full_description' => 'Crafted for executive travel, this sedan delivers whisper-quiet performance, adaptive ride control, and deeply cushioned seating.',
            'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Midnight Blue',
            'interior_color' => 'Navy Leather',
            'engine' => '3.0L Turbo Inline-6',
            'horsepower' => 429,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 5,
            'name' => '2026 Imperial Crest SUV',
            'slug' => '2026-imperial-crest-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 131250.00,
            'short_description' => 'Three-row luxury SUV with captain seating and air suspension.',
            'full_description' => 'A refined family-focused luxury SUV offering spacious third-row seating, air suspension, and first-class rear comfort.',
            'image_url' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Graphite Grey',
            'interior_color' => 'Sand Leather',
            'engine' => '3.5L Twin-Turbo V6',
            'horsepower' => 409,
            'transmission' => '10-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 7,
            'featured' => 0,
        ],
        [
            'id' => 6,
            'name' => '2026 Horizon GT Coupe',
            'slug' => '2026-horizon-gt-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 144900.00,
            'short_description' => 'Grand tourer with sculpted bodywork and twin-turbo power.',
            'full_description' => 'This grand tourer balances high-speed confidence with tailored cabin materials and a striking long-hood silhouette.',
            'image_url' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Arctic Silver',
            'interior_color' => 'Merlot Leather',
            'engine' => '4.0L Twin-Turbo V8',
            'horsepower' => 630,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 4,
            'featured' => 0,
        ],
        [
            'id' => 7,
            'name' => '2026 Sapphire Executive Sedan',
            'slug' => '2026-sapphire-executive-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 109400.00,
            'short_description' => 'Elegant sedan with rear executive package and soft-close doors.',
            'full_description' => 'A luxury sedan tailored for business-class comfort, with rear lounge seating and a serene cabin atmosphere.',
            'image_url' => 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Sapphire Blue',
            'interior_color' => 'Ivory Leather',
            'engine' => '3.0L Turbo Inline-6',
            'horsepower' => 375,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 8,
            'name' => '2026 Arctic Crown SUV',
            'slug' => '2026-arctic-crown-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 124700.00,
            'short_description' => 'Luxury utility with heated captain seats and terrain drive modes.',
            'full_description' => 'Built for year-round confidence, this upscale SUV pairs polished road manners with adaptable terrain systems.',
            'image_url' => 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Glacier White',
            'interior_color' => 'Charcoal Leather',
            'engine' => '3.0L Turbo Inline-6 Hybrid',
            'horsepower' => 434,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 9,
            'name' => '2026 Onyx Aero Coupe',
            'slug' => '2026-onyx-aero-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 152300.00,
            'short_description' => 'Aerodynamic fastback coupe with ceramic brakes and launch control.',
            'full_description' => 'Precision-focused and dramatic, the Onyx Aero Coupe delivers thrilling acceleration with a beautifully minimalist cockpit.',
            'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Onyx Black',
            'interior_color' => 'Crimson Leather',
            'engine' => '4.4L Twin-Turbo V8',
            'horsepower' => 671,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 4,
            'featured' => 0,
        ],
        [
            'id' => 10,
            'name' => '2026 Regent Hybrid Sedan',
            'slug' => '2026-regent-hybrid-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 98750.00,
            'short_description' => 'Efficiency-minded flagship with hybrid power and massage seating.',
            'full_description' => 'A smooth and intelligent hybrid sedan with a calm ride, premium audio, and eco-conscious luxury engineering.',
            'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Quartz Silver',
            'interior_color' => 'Pearl Beige',
            'engine' => '2.5L Turbo Hybrid',
            'horsepower' => 348,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Front-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 11,
            'name' => '2026 Summit Signature SUV',
            'slug' => '2026-summit-signature-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 138200.00,
            'short_description' => 'Flagship SUV with executive second row and premium tow package.',
            'full_description' => 'A commanding SUV that combines full-size comfort, luxury appointments, and advanced driver assistance for long-distance touring.',
            'image_url' => 'https://images.unsplash.com/photo-1498887960847-2a5e46312788?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Deep Navy',
            'interior_color' => 'Cognac Leather',
            'engine' => '3.5L Twin-Turbo V6',
            'horsepower' => 440,
            'transmission' => '10-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 7,
            'featured' => 0,
        ],
        [
            'id' => 12,
            'name' => '2026 Valencia Sport Coupe',
            'slug' => '2026-valencia-sport-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 149800.00,
            'short_description' => 'Italian-inspired coupe with adaptive dampers and vivid styling.',
            'full_description' => 'This exotic-influenced coupe pairs sharp proportions with high-revving excitement and a driver-focused cockpit.',
            'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Rosso Red',
            'interior_color' => 'Black Leather',
            'engine' => '3.9L Twin-Turbo V8',
            'horsepower' => 641,
            'transmission' => '7-Speed Dual Clutch',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 2,
            'featured' => 0,
        ],
        [
            'id' => 13,
            'name' => '2026 Grand Estate Sedan',
            'slug' => '2026-grand-estate-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 112600.00,
            'short_description' => 'Long-wheelbase comfort with lounge seating and rear media screens.',
            'full_description' => 'Designed for chauffeur-level comfort, the Grand Estate Sedan blends generous cabin space with understated elegance.',
            'image_url' => 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Champagne Silver',
            'interior_color' => 'Mocha Leather',
            'engine' => '3.0L Turbo Inline-6',
            'horsepower' => 402,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 14,
            'name' => '2026 Meridian Luxe SUV',
            'slug' => '2026-meridian-luxe-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 127300.00,
            'short_description' => 'Luxury crossover with ventilated seating and immersive audio.',
            'full_description' => 'The Meridian Luxe SUV is tuned for comfort-first travel, with premium audio, a wide panoramic roof, and confident all-weather handling.',
            'image_url' => 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Moonstone Grey',
            'interior_color' => 'Ivory Leather',
            'engine' => '3.0L Turbo Inline-6',
            'horsepower' => 395,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 15,
            'name' => '2026 Carbon Halo Coupe',
            'slug' => '2026-carbon-halo-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 158900.00,
            'short_description' => 'High-performance coupe with active aero and carbon roof.',
            'full_description' => 'The Carbon Halo Coupe is purpose-built for exhilarating road presence, with active aerodynamics and track-ready composure.',
            'image_url' => 'https://images.unsplash.com/photo-1503736028674-451b2cb67b32?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Storm Grey',
            'interior_color' => 'Black Alcantara',
            'engine' => '5.2L Twin-Turbo V10',
            'horsepower' => 710,
            'transmission' => '8-Speed Dual Clutch',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 2,
            'featured' => 0,
        ],
        [
            'id' => 16,
            'name' => '2026 Heritage Line Sedan',
            'slug' => '2026-heritage-line-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 102400.00,
            'short_description' => 'Classic-inspired styling with modern digital cockpit features.',
            'full_description' => 'A tasteful executive sedan with heritage design cues, polished wood trim, and intuitive technology integration.',
            'image_url' => 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'British Racing Green',
            'interior_color' => 'Tan Leather',
            'engine' => '2.9L Twin-Turbo V6',
            'horsepower' => 362,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 17,
            'name' => '2026 Atlas Prestige SUV',
            'slug' => '2026-atlas-prestige-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 133600.00,
            'short_description' => 'Prestige SUV with off-road package and executive cabin finishes.',
            'full_description' => 'A luxury SUV that blends elevated daily comfort with extra capability for destination travel beyond the city.',
            'image_url' => 'https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Volcanic Black',
            'interior_color' => 'Camel Leather',
            'engine' => '4.0L Twin-Turbo V8',
            'horsepower' => 577,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 18,
            'name' => '2026 Riviera Grand Coupe',
            'slug' => '2026-riviera-grand-coupe',
            'category' => 'Coupe',
            'model_year' => 2026,
            'price' => 146500.00,
            'short_description' => 'Ocean-inspired grand coupe with panoramic roof and silk-smooth ride.',
            'full_description' => 'Built for elegant coastal journeys, the Riviera Grand Coupe pairs sculpted design with refined touring comfort.',
            'image_url' => 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Ocean Blue',
            'interior_color' => 'Cream Leather',
            'engine' => '4.0L Twin-Turbo V8',
            'horsepower' => 591,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'Rear-Wheel Drive',
            'seats' => 4,
            'featured' => 0,
        ],
        [
            'id' => 19,
            'name' => '2026 Platinum Voyager Sedan',
            'slug' => '2026-platinum-voyager-sedan',
            'category' => 'Sedan',
            'model_year' => 2026,
            'price' => 121900.00,
            'short_description' => 'Touring sedan with air suspension and rear comfort package.',
            'full_description' => 'A polished premium sedan focused on smooth highway travel, elegant materials, and full-day comfort.',
            'image_url' => 'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Platinum Silver',
            'interior_color' => 'Espresso Leather',
            'engine' => '3.0L Turbo Inline-6',
            'horsepower' => 389,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 5,
            'featured' => 0,
        ],
        [
            'id' => 20,
            'name' => '2026 Northstar Elite SUV',
            'slug' => '2026-northstar-elite-suv',
            'category' => 'SUV',
            'model_year' => 2026,
            'price' => 142750.00,
            'short_description' => 'Top-tier SUV with luxury seating, night vision, and concierge tech.',
            'full_description' => 'The Northstar Elite SUV offers flagship utility, advanced safety technology, and a deeply luxurious interior for every row.',
            'image_url' => 'https://images.unsplash.com/photo-1511391403284-6037f4c0f0b8?auto=format&fit=crop&w=900&q=80',
            'exterior_color' => 'Pearl White',
            'interior_color' => 'Navy Leather',
            'engine' => '4.4L Twin-Turbo V8',
            'horsepower' => 611,
            'transmission' => '8-Speed Automatic',
            'drivetrain' => 'All-Wheel Drive',
            'seats' => 7,
            'featured' => 0,
        ],
    ];
}

function getAllProducts(): array
{
    $pdo = getDatabaseConnection();

    if ($pdo === null) {
        return getFallbackProducts();
    }

    $statement = $pdo->query('SELECT * FROM products ORDER BY featured DESC, model_year DESC, name ASC');
    $products = $statement->fetchAll();

    return $products ?: getFallbackProducts();
}

function getProductById(int $id): ?array
{
    $pdo = getDatabaseConnection();

    if ($pdo === null) {
        foreach (getFallbackProducts() as $product) {
            if ((int) $product['id'] === $id) {
                return $product;
            }
        }

        return null;
    }

    $statement = $pdo->prepare('SELECT * FROM products WHERE id = :id LIMIT 1');
    $statement->execute(['id' => $id]);
    $product = $statement->fetch();

    return $product ?: null;
}

function formatPrice(float $price): string
{
    return '$' . number_format($price, 0);
}

function updateProduct(array $productData): array
{
    $pdo = getDatabaseConnection();

    if ($pdo === null) {
        return [false, 'Database connection is not available.'];
    }

    $requiredFields = [
        'id',
        'name',
        'category',
        'model_year',
        'price',
        'short_description',
        'full_description',
        'image_url',
        'engine',
        'horsepower',
        'transmission',
        'drivetrain',
        'seats',
        'exterior_color',
        'interior_color',
    ];

    foreach ($requiredFields as $field) {
        if (!isset($productData[$field]) || trim((string) $productData[$field]) === '') {
            return [false, 'Please fill in all product fields.'];
        }
    }

    $statement = $pdo->prepare(
        'UPDATE products
         SET name = :name,
             category = :category,
             model_year = :model_year,
             price = :price,
             short_description = :short_description,
             full_description = :full_description,
             image_url = :image_url,
             engine = :engine,
             horsepower = :horsepower,
             transmission = :transmission,
             drivetrain = :drivetrain,
             seats = :seats,
             exterior_color = :exterior_color,
             interior_color = :interior_color,
             featured = :featured
         WHERE id = :id'
    );

    $statement->execute([
        'id' => (int) $productData['id'],
        'name' => trim((string) $productData['name']),
        'category' => trim((string) $productData['category']),
        'model_year' => (int) $productData['model_year'],
        'price' => (float) $productData['price'],
        'short_description' => trim((string) $productData['short_description']),
        'full_description' => trim((string) $productData['full_description']),
        'image_url' => trim((string) $productData['image_url']),
        'engine' => trim((string) $productData['engine']),
        'horsepower' => (int) $productData['horsepower'],
        'transmission' => trim((string) $productData['transmission']),
        'drivetrain' => trim((string) $productData['drivetrain']),
        'seats' => (int) $productData['seats'],
        'exterior_color' => trim((string) $productData['exterior_color']),
        'interior_color' => trim((string) $productData['interior_color']),
        'featured' => isset($productData['featured']) ? 1 : 0,
    ]);

    return [true, 'Product updated successfully.'];
}
